name = "JuReto"
uuid = "7fe6cc6a-1977-40c0-8c64-97f76df8bbe5"
authors = ["takuma I <baru.poke.15@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
